### ISSUE TITLE
Unable to clear form input

### ISSUE THREAD

**Issue by bfrost2893** [fromAtoB/vue-stripe-elements#20]
Is there a way to expose the `clear` method on the Card? I would like to clear the form input after it has been submitted.

https://stripe.com/docs/stripe.js#other-methods

**Comment by softbeehive** [comment]
Hi Brad,
thanks for reporting it. It's part of a bigger problem. I think all native methods of stripe element should be available in Card and Card* components by default. Exposing `clear` method should be pretty easy, but instead of applying whitelist method patch I'd rather solve the global issue. I'll keep you updated.

**Comment by airandopal** [comment]
@bfrost2893 I found a workaround for the meantime
`this.$children[0].$children[0]._element.clear()`
....`this.` being the vue instance

**Comment by Failcookie** [comment]
@softbeehive - What is the current status of this?

**Comment by softbeehive** [comment]
I've been really busy last couple of months. Got a little bit of spare time to sort open-source issues out. Thanks for reminding, on it.

**Comment by Failcookie** [comment]
Any luck so far?

**Comment by softbeehive** [comment]
Planned to resolve this in major version release, but it doesn't make sense to wait. Major release preparations will take some time. Resolved in `0.2.8`. Will publish the new version today.

**Comment by Failcookie** [comment]
This is great to hear! Thank you for your work on this @softbeehive

**Comment by bfrost2893** [comment]
Thanks @softbeehive! Nice work 👍
